server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para evitar problemas de CORS adicionales si fuera necesario
    location /api/ {
        proxy_pass http://34.135.175.245:8080/;
    }
}
